### ISSUE TITLE
Compareset may crash when more alignments than sequences on the alignments are provided

### ISSUE THREAD

**Issue by Vicfero** [scapella/trimal#44] opened 2018-03-21 09:44 UTC
This is due to this line: [compareFiles.cpp:56](https://github.com/scapella/trimal/blob/d3bc8bffd25b0618cb534b1266c1f20efd2a362f/source/compareFiles.cpp#L56)

Currently:   numResiduesAlig = new int[numSeqs];

Should be: numResiduesAlig = new int[numAlignments];

**Comment by scapella** [comment] 2018-03-22 07:51
Duplicate of 45#

**Closed by scapella** 2018-03-22 07:51 UTC
